version: "3.9"  # optional since v1.27.0

services:
  db:
    container_name: ps_db
    image: postgres:14-alpine
    env_file:
      - ./.env
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

volumes:
  postgres_data:
