# Generated by Django 4.0.4 on 2022-06-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=110, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=150, verbose_name='Описание')),
                ('post_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('background_image', models.ImageField(upload_to='blog_post_background/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-post_time'],
            },
        ),
    ]
