# Generated by Django 4.0.4 on 2022-06-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=None, max_length=255, unique=True, verbose_name='Url'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='background_image',
            field=models.ImageField(upload_to='blog_post_background/%Y/%m/%d/', verbose_name='Картинка на фоне'),
        ),
    ]
