# Generated by Django 4.0.4 on 2022-07-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='post',
            name='background_image',
            field=models.ImageField(blank=True, default='blog_post_background/default/default_background_post.png', upload_to='blog_post_background/%Y/%m/%d/', verbose_name='Картинка на фоне'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название'),
        ),
    ]
