# Generated by Django 4.0.4 on 2022-07-11 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_is_archived'),
    ]

    operations = [
            migrations.RenameField('Post', 'post_time', 'creation_time')
    ]
