# Generated by Django 4.0.4 on 2022-07-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20220711_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog_gallery/%Y/%m/%d', verbose_name='Картинка в галереи')),
                ('thumbnail', models.ImageField(upload_to='blog_gallery_aside/%Y/%m/%d', verbose_name='Картинки в галереи 160x160')),
            ],
            options={
                'verbose_name': 'Картинку',
                'verbose_name_plural': 'Галерея',
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-creation_time'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
