# Generated by Django 4.0.4 on 2022-07-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_gallery_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='alt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='blog_gallery/%Y/%m/%d', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='blog_gallery_mini/%Y/%m/%d', verbose_name='Миниатюра'),
        ),
    ]
