# Generated by Django 4.0.4 on 2022-08-04 15:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_gallery_alt_alter_gallery_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=models.SET('Аноним'), to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='blog_post_background/%Y/%m/%d/', verbose_name='Картинка на фоне'),
        ),
    ]
