# Generated by Django 4.0.4 on 2022-08-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mywork',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default='2022-08-03 15:25:49.517017 +00:00', verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
