# Generated by Django 4.0.4 on 2022-06-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myclient',
            options={'ordering': ['name', '-created_at'], 'verbose_name': 'Моего клиента', 'verbose_name_plural': 'Мои клиенты'},
        ),
        migrations.AlterModelOptions(
            name='mywork',
            options={'ordering': ['title'], 'verbose_name': 'Мою работу', 'verbose_name_plural': 'Мои работы'},
        ),
        migrations.AddField(
            model_name='mywork',
            name='picture',
            field=models.ImageField(blank=True, upload_to='my_works/%Y/%m/%d/', verbose_name='Картина'),
        ),
    ]
