# Generated by Django 4.0.4 on 2022-08-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_mywork_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywork',
            name='picture',
            field=models.ImageField(upload_to='my_works/%Y/%m/%d/', verbose_name='Картина'),
        ),
    ]
