# Generated by Django 4.0.4 on 2022-06-10 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_myclient_options_alter_mywork_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myclient',
            options={'ordering': ['name', '-created_at', '-updated_at'], 'verbose_name': 'Моего клиента', 'verbose_name_plural': 'Мои клиенты'},
        ),
    ]
