# Generated by Django 4.0.4 on 2022-08-04 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название профессии')),
            ],
            options={
                'verbose_name': 'Профессию',
                'verbose_name_plural': 'Профессии',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='about',
            field=models.TextField(default='about defoult text', verbose_name='О себе'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
        migrations.CreateModel(
            name='ProfessionsCustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.professions')),
            ],
            options={
                'verbose_name': 'Профессию1',
                'verbose_name_plural': 'Профессии2',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='profession',
            field=models.ManyToManyField(through='users.ProfessionsCustomUser', to='users.professions', verbose_name='Профессии'),
        ),
    ]
