# Generated by Django 4.0.4 on 2022-08-04 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_professions_customuser_about_alter_customuser_avatar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professionscustomuser',
            options={},
        ),
        migrations.AlterField(
            model_name='professionscustomuser',
            name='custom_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='professionscustomuser',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.professions', verbose_name='Профессия'),
        ),
    ]
